name: Windows
on:
  push:
    branches: [ gazebo11 ]
  pull_request:
    branches: [ gazebo11 ]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  configure:
    name: ${{ matrix.arch }}-configure
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - arch: x64
        - arch: x86
    steps:
      - uses: actions/checkout@v3    
      - uses: .github/workflows/windows-configure@v1
        with:
          arch: ${{ matrix.arch }}

  build:
    name: ${{ matrix.arch }}-build
    runs-on: windows-latest
    needs: configure
    strategy:
      fail-fast: false  
      matrix:
        include:
        - arch: x64
        - arch: x86  
    steps:
      - uses: actions/checkout@v3
      - uses: .github/workflows/windows-configure@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Build Gazebo
        shell: cmd
        run: |
          cmake --build build --config Release

      - name: Install Gazebo
        shell: cmd
        run: |
          cmake --install build --config Release
          
      - name: Tests suite compilation
        shell: cmd
        run: |
          echo compile and run tests here

      - name: Prepare logs on failure
        if: failure()
        shell: cmd
        run: |
          7z a -t7z -r -mx=9 logs.7z ^
              vcpkg/buildtrees/*.log ^
              build/.ninja_log ^
              build/build.ninja ^
              build/install_manifest.txt ^
              build/vcpkg-manifest-install.log

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: windows_logs_${{matrix.arch}}_${{github.event.pull_request.head.sha}}
          path: logs.7z

      - name: Prepare artifacts for deploy
        if: success()
        shell: cmd
        run: |
          move vcpkg\installed\%arch%-windows-release vcpkg\installed\gazebo

      - name: Upload gazebo
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: windows_${{matrix.arch}}_${{github.event.pull_request.head.sha}}
          path: vcpkg\installed\gazebo
